.\" Manpage for gfal-save
.\"
.TH GFAL-LEGACY-REGISTER 1 "December 2014" "v1.2.0"
.SH NAME
gfal-legacy-register \- register a replica
.SH SYNOPSIS
.B gfal-legacy-register
[
.B "-h"
] [
.B -V
] [
.B -v
] [
.B -D
.I DEFINITION
] [
.B -C
.I CLIENT-INFO
] [
.B -t
.I TIMEOUT
] \fI lfc surl\fR

.SH DESCRIPTION
.B gfal-legacy-register
Register a new replica into a catalog

.SH OPTIONS
.TP
.B "-h, --help"
show help about the command.
.TP
.B "-V, --version"
output version information and exit.
.TP
.B "-v, --verbose"
verbose mode. Repeat up to 3 times for the most verbose mode.
.TP
.B "-D, --definition"
define properties for gfal2.
.TP
.B "-C, --client-info"
provide custom client-side information
.TP
.B "-t, --timeout"
global timeout for the execution of the command. Command is interrupted if time expires before it finishes.
.TP
.B lfc
LFC entry (lfc:// or guid:)
.TP
.B surl
Site URL

.SH EXAMPLES
.TP
.B gfal-legacy-register
guid:12345-678-abcdef
srm://endpoint.cern.ch/path/group

.SH FILES
.I /etc/gfal2.d/*
.RS
All configuration files in this directory affect the behavior of the underlying gfal2.

.SH AUTHORS
Duarte Meneses <duarte.meneses@cern.ch>
.br
Adrien Devresse <adrien.devresse@cern.ch>
.br
Alejandro Alvarez Ayllon <alejandro.alvarez.ayllon@cern.ch>

.SH "SEE ALSO"
.BR gfal-legacy-replicas (1),
.BR gfal-legacy-unregister (1)
