.\" Manpage for gfal-copy
.\"
.TH GFAL-COPY 1 "May 2017" "v1.5.0"
.SH NAME
gfal-copy \- Copy files
.SH SYNOPSIS
.B gfal-copy
[
.I OPTION
]...
.I SOURCE
.I DEST1 [ DEST2 ... ]

.SH DESCRIPTION
.B gfal-copy
Copies files from source to destination(s). If several destinations are specified, the file will be copy in a chain: src -> dst1, dst1 -> dst2, ... If used in an interactive console, transfer information will be giving during the copy, which varies depending on the available information. This command can be used to upload local files to remote file systems and to register files in the file catalog (see examples).

.SH OPTIONS
.TP
.B "-h, --help"
show help about the command.
.TP
.B "-V, --version"
output version information and exit.
.TP
.B "-v, --verbose"
verbose mode. Repeat up to 3 times for the most verbose mode.
.TP
.BI "-D, --definition"
define properties for gfal2.
.TP
.BI "-C, --client-info"
provide custom client-side information
.TP
.BI "-t, --timeout " TIMEOUT
maximum time for the operation to terminate - default is 1800 seconds. This timeout is enforced by gfal2-util, so it
applies to the overall operation. It should be greater or equal than --transfer-timeout.
.TP
.BI "-E, --cert " CERT
user certificate
.TP
.BI "--key " KEY
user private key
.TP
.B "-4"
Forces gfal2-util to use IPv4 addresses only
.TP
.B "-6"
Forces gfal2-util to use IPv6 addresses only
.TP
.B "-f, --force"
if destination file(s) cannot be overwritten, delete it and try again
.TP
.B "-p, --parent"
if the destination directory does not exist, create it
.TP
.BI "-n, --nbstreams " NBSTREAMS
specify the maximum number of parallel streams to use for the copy
.TP
.BI "--tcp-buffersize " TCP_BUFFERSIZE
specify the TCP buffersize
.TP
.BI "-s, --src-spacetoken " SRC_SPACETOKEN
source spacetoken to use for the transfer
.TP
.BI "-S, --dst-spacetoken " DST_SPACETOKEN
destination spacetoken to use for the transfer
.TP
.BI "-T, --transfer-timeout " TRANSFER_TIMEOUT
timeout for the transfer operation. This timeout is enforced by each plugin, so it applies to the transfer operation
only.
.TP
.BI "-K, --checksum " CHECKSUM
checksum algorithm to use, or algorithm:value
.TP
.BI "--from-file " FROM_FILE
read sources from a file
.TP
.B "--just-copy"
just do the copy and skip any preparation (i.e. checksum, overwrite, etc.)


.SH EXAMPLES
.TP
Copy a file to srm://endpoint.cern.ch/path/group, preferring a protocol as specified in the configuration file:
.B gfal-copy file:///etc/group srm://endpoint.cern.ch/path/
.PP
.TP
You can specify directly a protocol, if you know that it is supported by the end point:
.B gfal-copy file:///tmp/test gsiftp://endpoint.cern.ch/path/test
.PP
.TP
.TP
Do a chained copy:
.B gfal-copy file:///tmp/test gsiftp://endpoint.cern.ch/path/test file:///tmp/test2
.PP
.TP
Registration of a file in the LFC:
.B gfal-copy file:///tmp/source gsiftp://endpoint.cern.ch/path/test lfc://lfc-host.cern.ch/lfn

.SH FILES
.I /etc/gfal2.d/*
.RS
All configuration files in this directory affect the behavior of the underlying gfal2, in particular, the default choice of transfer protocols.

.SH AUTHORS
Duarte Meneses <duarte.meneses@cern.ch>
.br
Adrien Devresse <adrien.devresse@cern.ch>
.br
Alejandro Alvarez Ayllon <alejandro.alvarez.ayllon@cern.ch>

.SH "SEE ALSO"
.BR gfal-copy (1),
.BR gfal-rm (1),
.BR gfal-cat (1),
.BR gfal-save (1),
.BR gfal-mkdir (1),
.BR gfal-ls (1),
.BR gfal-xattr (1)
