.\" Manpage for gfal-sum
.\"
.TH GFAL-SUM 1 "March 2022" "v1.7.1"
.SH NAME
gfal-sum \- Calculate checksum of a file
.SH SYNOPSIS
.B gfal-sum
[
.I "OPTION"
]
.I "FILE CHECKSUM_TYPE"

.SH DESCRIPTION
.B gfal-sum
Calculates the checksum of the specified file, using a specified checksum algorithm. The supported algorithm depend on the protocol and endpoint. Some examples are
.I ADLER32
,
.I CRC32
and
.I MD5

.SH OPTIONS
.TP
.B "-h, --help"
show help about the command.
.TP
.B "-V, --version"
output version information and exit.
.TP
.B "-v, --verbose"
verbose mode. Repeat up to 3 times for the most verbose mode.
.TP
.BI "-D, --definition " DEFINITION
define properties for gfal2. Definitions have the following syntax: "CONFIG_GROUP:KEY=VALUE"
.TP
.BI "-t, --timeout " TIMEOUT
global timeout for the execution of the command. Command is interrupted if time expires before it finishes. Note: A grace period of 30 seconds is given to the global timeout.
.TP
.BI "-E, --cert " CERT
user certificate. (This option takes effect only after X509_USER_PROXY environment variable and default /tmp/x509up_u`id -u` location cannot provide a certificate)
.TP
.BI "--key " KEY
user private key.
.TP
.B "-4"
forces Gfal2 to use IPv4 addresses only. (Option valid only for GridFTP protocol)
.TP
.B "-6"
forces Gfal2 to use IPv6 addresses only. (Option valid only for GridFTP protocol)
.TP
.BI "-C, --client-info " CLIENT_INFO
provide custom client-side information.
.TP
.BI "--log-file " LOG_FILE
write Gfal2 library logs to the given file location.

.SH EXAMPLES
.TP
.B gfal-sum
srm://endpoint.cern.ch/path/file ADLER32

.SH FILES
.I /etc/gfal2.d/*
.RS
All configuration files in this directory affect the behavior of the underlying gfal2.

.SH AUTHORS
Duarte Meneses <duarte.meneses@cern.ch>
.br
Adrien Devresse <adrien.devresse@cern.ch>
.br
Alejandro Alvarez Ayllon <alejandro.alvarez.ayllon@cern.ch>
.br
Andrea Manzi <andrea.manzi@cern.ch>
.br
Mihai Patrascoiu <mihai.patrascoiu@cern.ch>
.br
Joao Lopes <joao.pedro.batista.lopes@cern.ch>

.SH "SEE ALSO"
.BR gfal-cat (1),
.BR gfal-chmod (1),
.BR gfal-copy (1),
.BR gfal-ls (1),
.BR gfal-mkdir (1),
.BR gfal-rename (1),
.BR gfal-rm (1),
.BR gfal-save (1),
.BR gfal-stat (1),
.BR gfal-sum (1),
.BR gfal-token (1),
.BR gfal-xattr (1),
.BR gfal-evict (1),
.BR gfal-bringonline (1),
.BR gfal-archivepoll (1)
