#!/usr/bin/env python3
## gfal 2.0 command line tools
## @author Adrien Devresse <adevress@cern.ch> CERN
## @author Duarte Meneses <duarte.meneses@cern.ch> CERN
## @author Andrea Manzi <amanzi@cern.ch> CERN
## @license GPLv3
##

from gfal2_util.shell import Gfal2Shell
import sys

if __name__ == "__main__":
        sys.exit(Gfal2Shell().main(sys.argv))
