#!/usr/bin/env python2
## gfal 2.0 command line tools
## @license GPLv3
##

from gfal2_util.shell import Gfal2Shell
import sys

if __name__ == "__main__":
        sys.exit(Gfal2Shell().main(sys.argv))
