#!/usr/bin/env python2
## gfal 2.0 command line tools
## @author Adrien Devresse <adevress@cern.ch> CERN
## @author Duarte Meneses <duarte.meneses@cern.ch> CERN
## @author Andrea Manzi <andrea.manzi@cern.ch> CERN
## @license GPLv3
##

from gfal2_util.shell import Gfal2Shell
import sys
import os

if __name__ == "__main__":
        os.environ["XrdSecGSIDELEGPROXY"] = "1"
        sys.exit(Gfal2Shell().main(sys.argv))
