#!/bin/sh
# -*- coding: utf-8 -*-
#
# Copyright (c) 2022 CERN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Execute script content with first python interpreter found:
# * GFAL_PYTHONBIN environment variable
# * python on the PATH if import gfal2, gfal2_util succeeds
# * python3 on the PATH if import gfal2, gfal2_util succeeds
# * python2 on the PATH if import gfal2, gfal2_util succeeds
# * /usr/bin/python
"exec" "$(  check_interpreter() { unalias $1 2> /dev/null; unset $1; GFAL_PYTHONBIN=$(command -v $1); [ $GFAL_PYTHONBIN ] && $GFAL_PYTHONBIN -c 'import gfal2, gfal2_util' > /dev/null 2>&1 && { echo $GFAL_PYTHONBIN; unset GFAL_PYTHONBIN; }; }; [ $GFAL_PYTHONBIN ] && echo $GFAL_PYTHONBIN || check_interpreter python || check_interpreter python3 || check_interpreter python2 || echo /usr/bin/python )" "-u" "-Wignore" "$0" "$@"

from gfal2_util.shell import Gfal2Shell
import sys

if __name__ == "__main__":
        sys.exit(Gfal2Shell().main(sys.argv))
